### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by j99thoms** [UBC-MDS/horror_movies#10]
When cleaning the data, we should probably drop observations which have a very low number for `vote_count`.  There are several movies in the dataset which have only 1 or 2 total votes and then have `vote_average=10.0`. 
Perhaps filter out observations which have `vote_count < 10` or something like that? 

@Hongjian-Sam-Li

**Comment by Hongjian-Sam-Li** [comment]
Good idea, thanks Jakob

**Comment by AguilarRaul** [comment]
Hi team, I think we can remove `poster_path` and `backdrop_path` columns, these two contain paths not relevant for us.  And maybe `tagline` and `overview` too since we are not doing any text mining.

**Comment by Hongjian-Sam-Li** [comment]
I removed (original_title,overview, tagline, poster_path, status, backdrop_path, collection, collection_name) since it seems that these cols won't have any help to our analysis

**Comment by j99thoms** [comment]
The `pre_process_horror.R` script doesn't need to be splitting the data into training and test sets because we aren't training any models. Our research question is inferential, not predictive. 

I'm going to tweak the script to adjust for this.

**Comment by j99thoms** [comment]
Also, the script should save to a directory called `clean`, not to the `raw` directory.

**Comment by j99thoms** [comment]
Done: https://github.com/UBC-MDS/horror_movies/commit/6026b3fa4650067d9b9d936efe15d698efc79a5a#diff-2296c5113f8e7763083394d0ae0312de9efd3df6594abb7e6dfef670082e077c
