### ISSUE TITLE
Final push for milestone 2 submission

### ISSUE THREAD

**Issue by j99thoms** [UBC-MDS/horror_movies#21]
Ok final push, team! We still need:
- an .Rmd or .ipynb files that presents the key useful (not all!) exploratory data analysis as well as the statistical summaries and figures in a little report. It should present the findings/results, and interpret the findings/results in context of the question. @Lorraine97 
- There's still a couple unchecked boxes on the feedback https://github.com/UBC-MDS/horror_movies/issues/11
- Just before submitting, create a release on the project repo named 0.1.0.
- Then submit to Canvas

**Comment by j99thoms** [comment]
For the canvas submission:
- You must include the URL of the project’s repository in your milestone 2 submission to Canvas
- Also include a URL to the release named 0.1.0 in your milestone 2 submission to Canvas

**Comment by Lorraine97** [comment]
@J99thoms I just made release https://github.com/UBC-MDS/horror_movies/releases/tag/0.1.0

Will submit to Canvas now.
