### ISSUE TITLE
Correct the project base on the Issue: Milestone 2 Grades #25

### ISSUE THREAD

**Issue by Hongjian-Sam-Li** [UBC-MDS/horror_movies#31]
Each of us can select no less than 5 bullet points in TA's comment to finer the project.

**Comment by Lorraine97** [comment]
@Hongjian-Sam-Li since we now realize there are only 4 items to fix, let's close this one! We will pick new items in the new issue here 

https://github.com/UBC-MDS/horror_movies/issues/38
https://github.com/UBC-MDS/horror_movies/issues/37
https://github.com/UBC-MDS/horror_movies/issues/36
