### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by Hongjian-Sam-Li** [UBC-MDS/horror_movies#4]
I updated 2 graphs with a little explanation in the new branch [horror_movies_data_EDA_2](https://github.com/UBC-MDS/horror_movies/tree/horror_movies_data_EDA_2).  Please check if those plots make sense to you. If everything is ok we can start wrting text to those graphs.

**Comment by AguilarRaul** [comment]
I think there was not need to create a new branch,  I deleted mine (let's keep yours). As per the EDA, yeah sure I will add some comments to my plots and then I'll merge to the main.

**Comment by Lorraine97** [comment]
> I think there was not need to create a new branch, I deleted mine (let's keep yours). As per the EDA, yeah sure I will add some comments to my plots and then I'll merge to the main.

Just a reminder that each of us should push a branch of his/her own and initiate a PR.

**Comment by AguilarRaul** [comment]
Missed that one, thank you.
