### ISSUE TITLE
Feedback implemented

### ISSUE THREAD

**Issue by AguilarRaul** [UBC-MDS/horror_movies#40]
Five pieces of feedback that have been implemented:

1. [Peer review feedback] In the EDA script, more comments and documentation could be added so that it is easy for the reader to understand the script.
Commit URL: https://github.com/UBC-MDS/horror_movies/commit/b95931e7f50162474832746202418d392fbee0b5
https://github.com/UBC-MDS/horror_movies/commit/95a0645f5373fde8ef731929bb4ed8ca21bae7b4
File Changed: src/eda_horror.R

2. [TA feedback]  Figure captions missing
Commit URL: https://github.com/UBC-MDS/horror_movies/commit/bfd30bba27fbe09b092ee469cd1ac11537376606
File Changed: src/inference_horror.R

3. [TA feedback] The proposal.md file has been created and moved to the doc directory -2 mechanics
Commit URL:  https://github.com/UBC-MDS/horror_movies/pull/32/commits/b21a94378f89f94f32fc0732053b754036361c6b
File Changed: doc/proposal.md

4. [TA feedback] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels
Commit URL: https://github.com/UBC-MDS/horror_movies/pull/41/commits/b99dbe0c7fd5642c1db521d8155fc955bfc2f64a
File Changed: notebooks/Horror_movies_attributes_and_revenue_EDA.ipynb, src/eda_horror.R

5. [Peer review] The final report was named EDA_keys.ipynb, which made it hard for me to understand which was the final report. The naming of the report file could be improved. (eg : {name of the project}_report.ipynb)
Commit URL:  https://github.com/UBC-MDS/horror_movies/commit/094d7534728707b4d908465dc50ff674dc55596f
File Changed: report.ipynb

**Comment by AguilarRaul** [comment]
Hi team, above our 5 points of feedback, I will add the comment [here](https://github.com/UBC-MDS/data-analysis-review-2022/issues/22) once we are done. Feel free to add extra bullets.

**Comment by j99thoms** [comment]
https://github.com/UBC-MDS/horror_movies/commit/094d7534728707b4d908465dc50ff674dc55596f

**Comment by AguilarRaul** [comment]
Added the comment to the shared repo.
